"""Stdlib-only base for local diff/compare-tool UI servers.

Shared plumbing extracted from dct's and mct's UI servers: port probing,
a `{url_marker}={url}` marker line for parent CLIs to scrape, no-store JSON/
file/bytes serving, request-body reading, graceful shutdown — and shared
request protection for every route.

Every request passes ``_guard`` before any route handler runs:

- ``Host`` must name the actual bound port on an explicit loopback address
  (127.0.0.1 / localhost / [::1]) — rejects DNS-rebinding and foreign Hosts.
- A supplied ``Origin`` must be same-origin on the bound port; ``null`` and
  foreign origins are rejected.
- ``/api/*`` routes additionally require the ``X-MCT-Token`` header to carry
  the per-server session token generated by ``serve_ui``. The token is
  delivered only through the same-origin bootstrap HTML (see
  ``_serve_bootstrap_html``); it never appears in URLs, logs, or exports.
  Non-browser clients without ``Origin`` authenticate the same way.
- JSON bodies must declare ``application/json``, have a well-formed
  ``Content-Length`` under the size cap, and parse to a JSON object.

Rejection happens before file access, writes, subprocess creation, or SSE
setup. No permissive CORS: OPTIONS and cross-origin requests get no
Access-Control headers at all.
"""
from __future__ import annotations

import errno
import json
import secrets
import sys
import threading
import webbrowser
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse

NO_STORE_HEADERS = {
    "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
    "Pragma": "no-cache",
}

TOKEN_HEADER = "X-MCT-Token"
MAX_BODY_BYTES = 1_000_000
_ALLOWED_HOST_NAMES = {"127.0.0.1", "localhost", "::1", "[::1]"}
_JSON_CT = "application/json"


class UIHTTPServer(HTTPServer):
    allow_reuse_address = True
    # Set by serve_ui() after binding — one unpredictable token per server
    # instance, read by the handler via self.server.session_token.
    session_token: str = ""


class BaseUIHandler(SimpleHTTPRequestHandler):
    """Common request plumbing. Subclasses implement ``_route_GET`` /
    ``_route_POST`` / ``_route_DELETE`` (the base's do_* methods run the
    shared guard first) and call the _serve_* helpers below; they should not
    need to touch send_response directly for JSON/file/byte responses."""

    def log_message(self, format, *args):
        pass

    def handle_one_request(self):
        try:
            super().handle_one_request()
        except (BrokenPipeError, ConnectionResetError):
            pass

    # ------------------------------------------------------------------
    # Guarded verb dispatch: the guard runs before any route handler, so a
    # rejected request can never reach file access, writes, subprocesses,
    # or SSE setup.
    # ------------------------------------------------------------------

    def do_GET(self):
        self._dispatch("GET")

    def do_POST(self):
        self._dispatch("POST")

    def do_DELETE(self):
        self._dispatch("DELETE")

    def do_OPTIONS(self):
        self._dispatch("OPTIONS")

    def do_HEAD(self):
        # Without this, HEAD inherits SimpleHTTPRequestHandler's filesystem
        # serving — bypassing the Host/Origin/token guard entirely.
        self._dispatch("HEAD")

    def _dispatch(self, verb: str):
        if not self._guard():
            return
        route = getattr(self, f"_route_{verb}", None)
        if route is None:
            # OPTIONS (and any unimplemented verb) get no CORS headers — the
            # browser treats that as a failed preflight for foreign pages.
            self.send_error(405)
            return
        route()

    # ------------------------------------------------------------------
    # Guard checks
    # ------------------------------------------------------------------

    def _guard(self) -> bool:
        """True when the request may proceed; otherwise a rejection response
        has already been sent."""
        if not self._host_allowed():
            self._serve_json({"ok": False, "error": "Forbidden"}, 403)
            return False
        if not self._origin_allowed():
            self._serve_json({"ok": False, "error": "Forbidden"}, 403)
            return False
        if self._is_api_path() and not self._token_ok():
            self._serve_json({"ok": False, "error": "Forbidden"}, 403)
            return False
        return True

    def _bound_port(self) -> int:
        addr = self.server.server_address
        if isinstance(addr, tuple) and len(addr) >= 2:
            return int(addr[1])
        return -1

    def _host_allowed(self) -> bool:
        host = (self.headers.get("Host") or "").strip()
        if not host:
            return False
        if host.startswith("["):
            # [ipv6]:port
            name, sep, port = host.partition("]:")
            if not sep:
                return False
            name += "]"
        else:
            name, sep, port = host.rpartition(":")
            if not sep:
                return False
        return name in _ALLOWED_HOST_NAMES and port == str(self._bound_port())

    def _origin_allowed(self) -> bool:
        origin = (self.headers.get("Origin") or "").strip()
        if not origin:
            return True  # non-browser clients authenticate via token instead
        port = self._bound_port()
        return origin in {
            f"http://127.0.0.1:{port}",
            f"http://localhost:{port}",
            f"http://[::1]:{port}",
        }

    def _is_api_path(self) -> bool:
        return urlparse(self.path).path.startswith("/api/")

    def _token_ok(self) -> bool:
        expected = getattr(self.server, "session_token", "")
        supplied = self.headers.get(TOKEN_HEADER) or ""
        return bool(expected) and secrets.compare_digest(expected, supplied)

    # ------------------------------------------------------------------
    # Serving helpers
    # ------------------------------------------------------------------

    def _serve_bootstrap_html(self, filepath: Path):
        """Serve an HTML shell with the session token injected as a same-origin
        bootstrap script. Only same-origin pages receive the token this way —
        foreign pages are rejected by the Origin check, and the token never
        appears in URLs or exported artifacts."""
        text = filepath.read_text(encoding="utf-8")
        token = getattr(self.server, "session_token", "")
        script = f"<script>window.__MCT_TOKEN__={json.dumps(token)};</script>"
        if "<body>" in text:
            text = text.replace("<body>", f"<body>{script}", 1)
        else:
            text = script + text
        self._serve_bytes(
            text.encode("utf-8"), 200, {"Content-Type": "text/html; charset=utf-8"}
        )

    def _read_body(self) -> dict | None:
        """Validated JSON object body, or None after a rejection response was
        sent (caller must return immediately). Enforces Content-Length sanity,
        size cap, JSON content type, and object shape."""
        raw_len = self.headers.get("Content-Length")
        if raw_len is None:
            return {}
        try:
            length = int(raw_len)
        except ValueError:
            self._serve_json({"ok": False, "error": "Malformed Content-Length"}, 400)
            return None
        if length < 0:
            self._serve_json({"ok": False, "error": "Malformed Content-Length"}, 400)
            return None
        if length == 0:
            return {}
        if length > MAX_BODY_BYTES:
            self._serve_json(
                {"ok": False, "error": "Request body too large"}, 413
            )
            return None
        ctype = (self.headers.get("Content-Type") or "").split(";")[0].strip().lower()
        if ctype != _JSON_CT:
            self._serve_json(
                {"ok": False, "error": "Content-Type must be application/json"}, 415
            )
            return None
        try:
            data = json.loads(self.rfile.read(length).decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            self._serve_json({"ok": False, "error": "Malformed JSON body"}, 400)
            return None
        if not isinstance(data, dict):
            self._serve_json(
                {"ok": False, "error": "JSON body must be an object"}, 400
            )
            return None
        return data

    def _serve_json(self, data, status: int = 200, filename: str | None = None):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        headers = {"Content-Type": "application/json; charset=utf-8"}
        if filename:
            headers["Content-Disposition"] = f'attachment; filename="{filename}"'
        self._serve_bytes(body, status, headers)

    def _serve_file(self, filepath: Path, content_type: str):
        if not filepath.is_file():
            self.send_error(404, f"File not found: {filepath}")
            return
        self._serve_bytes(filepath.read_bytes(), 200, {"Content-Type": f"{content_type}; charset=utf-8"})

    def _serve_bytes(self, body: bytes, status: int = 200, headers: dict | None = None):
        self.send_response(status)
        for key, value in (headers or {}).items():
            self.send_header(key, value)
        self.send_header("Content-Length", str(len(body)))
        for key, value in NO_STORE_HEADERS.items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(body)

    def _serve_sse(self, events):
        """Stream Server-Sent Events from an iterable of {"type": "data"|"done"|"error",
        "data": str} dicts — the framing kit/shell.js's Shell.streamPost() expects on
        the client. Typically fed by a generator that yields as a subprocess runs."""
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()
        try:
            for item in events:
                if item["type"] == "data":
                    msg = f"data: {item['data']}\n\n"
                elif item["type"] == "done":
                    msg = f"event: done\ndata: {item['data']}\n\n"
                else:
                    msg = f"event: error\ndata: {item['data']}\n\n"
                self.wfile.write(msg.encode("utf-8"))
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError):
            pass


def serve_ui(handler_cls: type[BaseUIHandler], port: int, url_marker: str, open_browser: bool = True) -> int:
    """Bind handler_cls to 127.0.0.1:port (or the next 40 ports if taken),
    print f"{url_marker}={url}" for the parent CLI to scrape, optionally open
    a browser, then serve until Ctrl+C. Returns a process exit code."""
    host = "127.0.0.1"
    want = int(port)
    server: UIHTTPServer | None = None
    chosen = want
    last_err: OSError | None = None

    for i in range(40):
        try:
            server = UIHTTPServer((host, chosen), handler_cls)
            break
        except OSError as e:
            last_err = e
            if e.errno != errno.EADDRINUSE:
                print(f"Could not bind UI to {host}:{chosen}: {e}", file=sys.stderr)
                return 1
            if i == 0:
                print(f"UI port {chosen} in use; trying {chosen + 1}, {chosen + 2}, ...", file=sys.stderr)
            chosen += 1
    if server is None:
        print(f"Could not bind UI after trying ports: {last_err}", file=sys.stderr)
        return 1

    server.session_token = secrets.token_urlsafe(32)

    chosen = server.server_address[1]  # authoritative — matters when port=0 (ephemeral)
    url = f"http://127.0.0.1:{chosen}"
    print(f"{url_marker}={url}", flush=True)
    print(f"\n  UI: {url}")
    print(f"  Press Ctrl+C to stop.\n")

    if open_browser:
        threading.Timer(0.5, lambda: webbrowser.open(url)).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.shutdown()

    return 0
